apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer-demo-depl
  labels:
    app: load-balancer-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-balancer-demo
  template:
    metadata:
      labels:
        app: load-balancer-demo
    spec:
      containers:
      - name: load-balancer-demo
        image: bzeki/load-balancer-demo:1.0
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: load-balancer-demo-service
spec:
  type: LoadBalancer
  selector:
    app: load-balancer-demo
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000