apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-port-demo-depl
  labels:
    app: node-port-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-port-demo
  template:
    metadata:
      labels:
        app: node-port-demo
    spec:
      containers:
      - name: node-port-demo
        image: bzeki/node-port-demo:1.1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: node-port-demo-service
spec:
  type: NodePort
  selector:
    app: node-port-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000