apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  type: LoadBalancer
  selector:
    app: http-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000