apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server-depl
  labels:
    app: http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: bzeki/http-server-study:1.0
        ports:
          - containerPort: 8080