apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-depl
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server-container
        image: bzeki/web-server
        ports:
        - containerPort: 8080